cli:
  - client/**/*
nix:
  - nix/**
  - default.nix
  - docker.nix
  - flake.nix

adr:
  - docs/architecture/**/*
build:
  - Makefile
  - Dockerfile
  - docker-compose.yml
  - scripts/*
ci:
  - .github/**
  - buf.work.yaml
  - .golangci.yml
